In [80]:
#---general purpose libraries--
import numpy as np
import pandas as pd
import os
#----for model bulding -----------
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
#---for model evaluation
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
#--for text processing----
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
import string
import re
#---for pipelining-----
from sklearn.pipeline import Pipeline

In [97]:
#--change the directory to your working directory where you have your training, sample input files
working_dir = input()
os.chdir(working_dir)

D:/Internshala/Mesh


In [94]:
#----------FUNCTION DEFINITIONS -------------------

#--function to preprocess text
#--> Removes numbers from the text
#--> Removes punctuation marks from the text
#--> Returns array
def preprocess(text):
    return re.findall(r'(?:[a-zA-Z]+[a-zA-Z\'\-]?[a-zA-Z]|[a-zA-Z]+)',text)

#--function to print performnace report-
def performance_report(true,pred):
    print(confusion_matrix(true, pred))
    print(classification_report(true, pred))
#----------FUNCTION DEFINITIONS ENDS HERE-------------------

In [89]:
#process the file which has user query and retreived procuct to create 2 create 2 different arrays product and user_query
training = open('training.txt')
product=[]
user_query=[]
first_line = 1
for line in training:
    if first_line==1:
        first_line = 0
        continue
    input_txt = line.strip().split("\t")
    processed_txt = ' '.join(txt for txt in preprocess(input_txt[0]))
    product.append(processed_txt)
    user_query.append(input_txt[1])
x_train=product
y_train=user_query

In [82]:
#create pipeline for vectorizing the text(also removes stop words) input and then creating model sequentially
x_train=product
y_train=user_query

#pred_model=Pipeline([('vectorize',TfidfVectorizer(stop_words='english')),('predictive_model', MultinomialNB())])
pred_model=Pipeline([('vectorize',TfidfVectorizer(stop_words='english')),
                   ('predictive_model', RandomForestClassifier())])
pred_model.fit(x_train,y_train)

Pipeline(memory=None,
     steps=[('vectorize', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=Tru...n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))])

In [83]:
#--process the sample input--
#--apply preprocessing on the text
test_prdct=[]
sample_input = open('Sample_Input.txt')

first_line = 1
for line in sample_input:
    if first_line==1:
        first_line = 0
        continue
    input_txt = line.strip()
    txt = ' '.join(preprocess(input_txt))
    test_prdct.append(txt)
x_test = np.array(test_prdct)

In [84]:
#--predict the corresponding query with the model
pred_query=pred_model.predict(x_test)

In [86]:
#Lets import sample output to compare with predicted output
test_user_query = []
sample_output = open('Sample_Output.txt') 
for line in sample_output:
    test_user_query.append(line.strip())

In [87]:
#--create dataframe to store the predicted Vs actual result
df_predicted_vs_actual = pd.DataFrame(
    {'Product': test_prdct,
     'Actual_User_Query': test_user_query,
     'Predicted_User_Query': pred_query
    })
#df_predicted_vs_actual

In [95]:
#--print the performance report
performance_report(df_predicted_vs_actual['Actual_User_Query'],df_predicted_vs_actual['Predicted_User_Query'])

[[3 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 3 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
                            precision    recall  f1-score   support

                   axe deo       0.75      0.60      0.67         5
         best-seller books       0.40      1.00      0.57         2
             c 

C:\Users\Home\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
#-----------------------------------------------------------------------------------------------